SR_KEY="2VPDBNSXSSV7HDX6"
SR_SECRET="q5x1jtr3kn3hK2sqFvdhs3iUPGHsNFUwWm13tx84MGaEF288ZZC4rRvsgcTBFj7u"
SR_URL="https://psrc-6zww3.us-east-2.aws.confluent.cloud"

API_KEY="NAP4OLXLMXHM7EZM"
API_SECRET="X9QAPkN83VfC5e0vdz5VseTwyZyCiBcx9id+ULJcuOM9nQ+Tt3oz6dzi+7lAZG3Q"
BOOTSTRAP_SERVER="pkc-ygz96.eastus.azure.confluent.cloud:9092"